### ISSUE TITLE
Options declaration causes an encoding error

### ISSUE THREAD

**Issue by tamarasaurus** [kjvalencik/gulp-mq-remove#1]
Using this syntax to specify the options object causes an error

``` javascript
.pipe(mqRemove({
        type : 'screen',
        width: '65em'
      }, {
    compress: true
   }))
```

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Unknown encoding: [object object]
    at Buffer.write (buffer.js:377:13)
    at new Buffer (buffer.js:215:28)
```

But it works if I change `line 63 in index.js` from

``` javascript
file.contents = new Buffer(css.stringify(mqRemove(query, file.contents)), options);
```

to putting it in the css.stringify function

``` javascript
file.contents = new Buffer(css.stringify(mqRemove(query, file.contents), options));
```

**Comment by kjvalencik** [comment]
@tamarasaurus, this fix has been published to npm as version `0.0.2`. Thanks again for your contribution.
